---
title: "Where Does The Buck Stop? Economic Conditions & Electoral Volatility"
author: "Karnav Popat & Shashwat Agarwal"
date: "21/03/2024"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: vignette
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(kableExtra)
library(sf)
library(raster)
library(exactextractr)
```

```{r data, include=FALSE}
partywise_votes <- read.csv("./data/partywise_voteshare_constituency.csv")

assembly_shp <- st_read("../shp/India_2014.geojson")
assembly_shp_old <- st_read("../shp/India_2013.geojson")
subdistricts_shp <- st_read("../shp/subdistrict.shp")
```

We can now calculate electoral volatility using the Pedersen formula:

``` {volatility}
# Calculate the volatility by summing the deltas for each party
partywise_deltas <- partywise_votes%>%
  group_by(State_Name, Constituency_No, Constituency_Name)%>%
  mutate_at(vars(starts_with("Party_")), 
            funs(abs(. - lag(.))))%>%
  mutate_all(~replace(., is.na(.), 0))%>%
  mutate_at(vars(matches("^Party")), as.numeric)%>%
  ungroup()%>%
  mutate(volatility=rowSums(dplyr::select(., starts_with("Party_")))/2)

volatility <- partywise_deltas%>%
  dplyr::select(State_Name, Constituency_No, Constituency_Name, Year, Assembly_No, volatility)%>%
  filter(volatility != 0)
```

``` {volatility_table, echo=FALSE}
kable(head(volatility, 10), caption="Volatility in Assembly Elections")%>%
  kable_styling(font_size=12)
write.csv(partywise_deltas, "./data/partywise_deltas_constituency.csv", row.names=FALSE)
write.csv(volatility, "./data/volatility_constituency.csv", row.names=FALSE)
```

``` {r read}
volatility <- read.csv("./data/volatility_constituency.csv")
```

This gives us our dependent variable, electoral volatility, at the constituency level.

``` {r boxplot_state, echo=FALSE}
# calculates the median value for each state
state_table <- volatility %>%
  group_by(State_Name)%>%
  summarise(median_vol=median(volatility), na.rm=TRUE)%>%
  arrange(median_vol)

volatility["State_Name"] <- factor(volatility$State_Name, levels = state_table$State_Name)

ggplot(volatility, aes(x = factor(State_Name), y = volatility)) +
  geom_boxplot() +
  labs(title = "Volatility by State") +
  xlab("State/UT") +
  ylab("% Volatiliy") +
  theme(axis.text.x = element_text(angle = 45))
```

``` {r boxplot_year, echo=FALSE}
ggplot(volatility, aes(x = factor(Year), y = volatility)) +
  geom_boxplot() +
  labs(title = "Volatility by Election") +
  xlab("Year") +
  ylab("% Volatiliy") +
  theme(axis.text.x = element_text(angle = 45))
```

``` {r line_year, echo=FALSE}

sum_volatility <- volatility %>%
  group_by(Year) %>%
  summarise(mean_volatility = mean(volatility))

ggplot(sum_volatility, aes(x = Year, y = mean_volatility)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") + 
  labs(title = "Volatility by Election") +
  xlab("Year") +
  ylab("% Volatiliy") +
  theme(axis.text.x = element_text(angle = 45)) +
  ylim(0, 100)
```


