---
title: "temp"
author: "Karnav Popat"
date: "2024-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(sf)
library(kableExtra)
library(tidyr)
library(dplyr)
library(stringr)
sf_use_s2(FALSE)
```

```{r data, include=FALSE}
matched_1990 <- st_read("./data/matched_dataset_1990.shp")
matched_1995 <- st_read("./data/matched_dataset_1995.shp")
matched_2000 <- st_read("./data/matched_dataset_2000.shp")
matched_2005 <- st_read("./data/matched_dataset_2005.shp")
matched_2010_1 <- st_read("./data/matched_dataset_2010_1.shp")
matched_2010_2 <- st_read("./data/matched_dataset_2010_2.shp")
matched_2015 <- st_read("./data/matched_dataset_2015.shp")
matched_2020 <- st_read("./data/matched_dataset_2020.shp")
```

``` {r append_old}
matched <- rbind(matched_1990, matched_1995)
matched <- rbind(matched, matched_2000)
matched <- rbind(matched, matched_2005)
matched <- rbind(matched, matched_2010_1)

matched <- matched%>%
  pivot_longer(cols = starts_with("ng_"),
                          names_to = "nightlight_year",
                          values_to = "nightlights")%>%
  mutate(election_year = Year)%>%
  mutate(volatility = voltlty)%>%
  mutate(delta_year = gsub("ng_", "", nightlight_year))%>%
  arrange(ac_name)

matched <- matched[, c("state", "ac_no", "ac_name", "Cnstt_N", "Assmb_N", "election_year", "volatility", "delta_year", "nightlights", "geometry")]

kable(head(matched))
kable(nrow(matched))
```

``` {r append_new}
matched_new <- rbind(matched_2010_2, matched_2015)
matched_new <- rbind(matched_new, matched_2020)

matched_new <- matched_new%>%
  pivot_longer(cols = starts_with("ng_"),
                          names_to = "nightlight_year",
                          values_to = "nightlights")%>%
  mutate(election_year = Year)%>%
  mutate(volatility = voltlty)%>%
  mutate(delta_year = gsub("ng_", "", nightlight_year))%>%
  arrange(ac_name)

matched_new <- matched_new[, c("state", "ac_no", "ac_name", "Cnstt_N", "Assmb_N", "election_year", "volatility", "delta_year", "nightlights", "geometry")]

kable(head(matched_new))
kable(nrow(matched_new))
```

``` {r append_total}
matched_data <- rbind(matched, matched_new)
matched_data <- matched_data%>%
  distinct(state, ac_no, ac_name, election_year, delta_year, .keep_all = TRUE)

kable(head(matched_data))
kable(nrow(matched_data))
```

``` {r write}
st_write(matched_data, "./data/matched_dataset.shp", delete_dsn = T)
```
