---
title: "Where Does The Buck Stop? Economic Conditions & Electoral Volatility"
author: "Karnav Popat & Shashwat Agarwal"
date: "21/03/2024"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: vignette
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(kableExtra)
library(sf)
library(raster)
library(exactextractr)
```

```{r data, include=FALSE}
# partywise_votes <- read.csv("./data/partywise_voteshare_constituency.csv")
# volatility <- read.csv("./data/volatility_constituency.csv")

panel_old <- st_read("./data/processed_dataset_old.shp")
panel_new <- st_read("./data/processed_dataset_new.shp")
```

``` {r preprocess}
panel <- rbind(panel_old, panel_new)

panel <- panel%>%
  rename(election_year = elctn_y,
         volatility = voltlty,
         delta_year = delt_yr,
         nightlights = nghtlgh,
         mean_nightlights = mn_nght,
         adjusted_nightlights = adjstd_,
         absolute_change = abslt_c,
         relative_change = rltv_ch,
         absolute_adj_change = abslt__,
         relative_adj_change = rltv_d_,
         past_three = pst_thr,
         absolute_change_p3 = absl__3,
         relative_change_p3 = rltv__3)

panel <- panel%>%
  filter(!is.na(relative_change_p3))%>%
  filter(is.finite(relative_change_p3))%>%
  filter(!is.na(volatility))%>%
  filter(is.finite(volatility))

st_geometry(panel) <- NULL

Q1 <- quantile(panel$relative_change, .25)
Q3 <- quantile(panel$relative_change, .75)
IQR <- IQR(panel$relative_change)

panel <- panel%>%
  filter((relative_change > (Q1 - 1.25*IQR)) & (relative_change < (Q3 + 1.25*IQR)))

kable(head(panel))
kable(nrow(panel))
```

``` {r model_1}
model1 <- lm(volatility ~ relative_change, data = panel)
summary(model1)

model2 <- lm(volatility ~ relative_change + election_year, data = panel)
summary(model2)

model3 <- lm(volatility ~ relative_change + (election_year * factor(state)), data = panel)
summary(model3)

ggplot(panel, aes(x = relative_change, y = volatility)) +
  geom_point() +
  geom_smooth(method = "lm", color = "blue") + 
  labs(title = "Our bivariate regression")

ggplot(panel, aes(x = relative_change, y = volatility)) +
  geom_point() +
  facet_wrap(~election_year) +
  geom_smooth(method = "lm", color = "blue") + 
  labs(title = "Our bivariate regression")
```

``` {r model_3}
model1 <- lm(volatility ~ relative_change_p3, data = panel)
summary(model1)

model2 <- lm(volatility ~ relative_change_p3 + election_year, data = panel)
summary(model2)

model3 <- lm(volatility ~ relative_change_p3 + (election_year * factor(state)), data = panel)
summary(model3)

ggplot(panel, aes(x = relative_change_p3, y = volatility)) +
  geom_point() +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "Our bivariate regression")

ggplot(panel, aes(x = relative_change_p3, y = volatility)) +
  geom_point() +
  facet_wrap(~election_year) +
  geom_smooth(method = "lm", color = "blue") + 
  labs(title = "Our bivariate regression")

```
