---
title: "Where Does The Buck Stop? Economic Conditions & Electoral Volatility"
author: "Karnav Popat & Shashwat Agarwal"
date: "21/03/2024"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: vignette
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(kableExtra)
library(sf)
library(raster)
library(zoo)
sf_use_s2(FALSE)
```

```{r data, include=FALSE}
# partywise_votes <- read.csv("./data/partywise_voteshare_constituency.csv")
# volatility <- read.csv("./data/volatility_constituency.csv")

data <- st_read("./data/matched_dataset_new.shp")
```

``` {r panel}
data <- data%>%
  rename(election_year = elctn_y,
         volatility = voltlty,
         delta_year = delt_yr,
         nightlights = nghtlgh)%>%
  filter(election_year > 1992)%>%
  filter(election_year > delta_year)%>%
  mutate_all(~replace(., is.na(.), 0))%>%
  group_by(delta_year)%>%
  mutate(mean_nightlights = mean(nightlights))%>%
  ungroup()%>%
  mutate(adjusted_nightlights = ((nightlights - mean_nightlights)/mean_nightlights) * 100)%>%
  group_by(state, ac_name)%>%
  mutate(absolute_change = nightlights - lag(nightlights, n=1))%>%
  mutate(relative_change = ((nightlights - lag(nightlights, n=1))/lag(nightlights, n=1)) * 100)%>%
  mutate(absolute_adj_change = adjusted_nightlights - lag(adjusted_nightlights, n=4))%>%
  mutate(relative_adj_change = ((adjusted_nightlights - lag(adjusted_nightlights, n=1))/lag(adjusted_nightlights, n=1)) * 100)%>%
  ungroup()%>%
  group_by(state, ac_name, election_year)%>%
  mutate(past_three = rollmean(nightlights, k = 3, fill = NA, align = "right"))%>%
  mutate(absolute_change_p3 = past_three - lag(past_three))%>%
  mutate(relative_change_p3 = ((past_three - lag(past_three))/lag(past_three)) * 100)%>%
  ungroup()

data <- data%>%
  filter((election_year-1) == delta_year)%>%
  filter(!is.na(relative_change))%>%
  filter(is.finite(relative_change))
```

``` {r tables, echo=FALSE}
kable(head(data))
kable(nrow(data))
```

``` {r write}
st_write(data, "./data/processed_dataset_new.shp", delete_dsn = T)
```

